on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build-prod

      - name: Send files to server
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.SFTP_IP }}
          FTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          METHOD: sftp
          PORT: 22
          LOCAL_DIR: './dist/antropogenez-dashboard/'
          REMOTE_DIR: '/var/www/html/antropogenez-dashboard'
